name = "ccozkan/hugo-coder"
license = "MIT"
licenselink = "https://github.com/ccozkan/hugo-coder/blob/master/LICENSE.md"
description = "Yet Another simple and clean blog theme for Hugo"
homepage = "https://github.com/ccozkan/hugo-coder/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "simple",
  "clean",
  "personal"
]
features = [
  "analytics",
  "favicon",
  "multilingual",
  "pagination",
  "single-column",
  "syntax-highlighting"
]
min_version = "0.77.0"

[author]
name = "C Çağrı Özkan"
homepage = "https://ozkan.cc"
